service: serverless-react
provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
functions:
# CloudFormation resource templates here
resources:
  # S3
  - ${file(resources/s3-bucket.yml)}
  # CloudFront
  - ${file(resources/cloudfront.yml)}
  # CodeBuild
  - ${file(resources/codebuild.yml)}
  # CodePipeline
  - ${file(resources/codepipeline.yml)}